text = (input('Please enter an integer number: '))

print(text[3])
print(text[-2])
print(text[0:5])
print(text[0:-2])
print(text[0:])
print(text[::-1])
print(text[-1::-1])
print (len(text))
